# Generated by Django 5.2 on 2025-10-26 13:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="customer_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "invoices_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bills_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payments_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        choices=[("Nos", "Nos"), ("Kgs", "Kgs"), ("Litres", "Litres")],
                        default="Nos",
                        max_length=10,
                    ),
                ),
                ("hsn_code", models.CharField(max_length=20, unique=True)),
                ("item_no", models.CharField(blank=True, max_length=20, null=True)),
                ("manage_sales_info", models.BooleanField(default=False)),
                (
                    "sales_selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sales_account",
                    models.CharField(blank=True, default="Sales", max_length=100),
                ),
                ("sales_description", models.TextField(blank=True)),
                ("manage_purchase_info", models.BooleanField(default=False)),
                (
                    "purchase_cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "purchase_account",
                    models.CharField(
                        blank=True, default="Cost of Goods Sold", max_length=100
                    ),
                ),
                ("purchase_description", models.TextField(blank=True)),
                ("track_inventory", models.BooleanField(default=False)),
                (
                    "opening_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "opening_stock_rate_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("individual", "Individual"),
                        ],
                        default="business",
                        max_length=20,
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("mr", "Mr"),
                            ("ms", "Ms"),
                            ("mrs", "Mrs"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("work_phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                ("pan", models.CharField(blank=True, max_length=20)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("AED", "AED"),
                            ("AUD", "AUD"),
                            ("BND", "BND"),
                            ("CAD", "CAD"),
                            ("CNY", "CNY"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("INR", "INR"),
                            ("JPY", "JPY"),
                            ("SAR", "SAR"),
                            ("USD", "USD"),
                            ("ZAR", "ZAR"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Current outstanding balance for this vendor. Updated automatically.",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("due_on_receipt", "Due on Receipt"),
                            ("net_7", "Net 7"),
                            ("net_15", "Net 15"),
                            ("net_30", "Net 30"),
                            ("net_45", "Net 45"),
                        ],
                        default="due_on_receipt",
                        max_length=20,
                    ),
                ),
                ("billing_attention", models.CharField(blank=True, max_length=255)),
                ("billing_country", models.CharField(blank=True, max_length=100)),
                ("billing_street1", models.CharField(blank=True, max_length=255)),
                ("billing_street2", models.CharField(blank=True, max_length=255)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_pin_code", models.CharField(blank=True, max_length=20)),
                ("billing_phone", models.CharField(blank=True, max_length=50)),
                ("billing_fax", models.CharField(blank=True, max_length=50)),
                ("shipping_attention", models.CharField(blank=True, max_length=255)),
                ("shipping_country", models.CharField(blank=True, max_length=100)),
                ("shipping_street1", models.CharField(blank=True, max_length=255)),
                ("shipping_street2", models.CharField(blank=True, max_length=255)),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_pin_code", models.CharField(blank=True, max_length=20)),
                ("shipping_phone", models.CharField(blank=True, max_length=50)),
                ("shipping_fax", models.CharField(blank=True, max_length=50)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Billorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Unpaid", "Unpaid"),
                            ("Paid Partially", "Paid Partially"),
                        ],
                        default="Unpaid",
                        max_length=15,
                    ),
                ),
                ("bill_date", models.DateField(db_index=True)),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("TDS", "TDS"), ("TCS", "TCS")],
                        default="TDS",
                        max_length=3,
                    ),
                ),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "tax_percentage",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5", "5%"),
                            ("12", "12%"),
                            ("18", "18%"),
                            ("28", "28%"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                (
                    "adjustments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                            ("None", "none"),
                        ],
                        default="None",
                        max_length=12,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillorderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("item_specification", models.TextField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("hsn_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bill_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billorder_items",
                        to="core.billorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("individual", "Individual"),
                        ],
                        default="business",
                        max_length=20,
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("mr", "Mr"),
                            ("ms", "Ms"),
                            ("mrs", "Mrs"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("work_phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                ("pan", models.CharField(blank=True, max_length=20)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("AED", "AED"),
                            ("AUD", "AUD"),
                            ("BND", "BND"),
                            ("CAD", "CAD"),
                            ("CNY", "CNY"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("INR", "INR"),
                            ("JPY", "JPY"),
                            ("SAR", "SAR"),
                            ("USD", "USD"),
                            ("ZAR", "ZAR"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Current outstanding balance for this customer. Updated automatically.",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("due_on_receipt", "Due on Receipt"),
                            ("net_7", "Net 7"),
                            ("net_15", "Net 15"),
                            ("net_30", "Net 30"),
                            ("net_45", "Net 45"),
                        ],
                        default="due_on_receipt",
                        max_length=20,
                    ),
                ),
                ("billing_attention", models.CharField(blank=True, max_length=255)),
                ("billing_country", models.CharField(blank=True, max_length=100)),
                ("billing_street1", models.CharField(blank=True, max_length=255)),
                ("billing_street2", models.CharField(blank=True, max_length=255)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_pin_code", models.CharField(blank=True, max_length=20)),
                ("billing_phone", models.CharField(blank=True, max_length=50)),
                ("billing_fax", models.CharField(blank=True, max_length=50)),
                ("shipping_attention", models.CharField(blank=True, max_length=255)),
                ("shipping_country", models.CharField(blank=True, max_length=100)),
                ("shipping_street1", models.CharField(blank=True, max_length=255)),
                ("shipping_street2", models.CharField(blank=True, max_length=255)),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_pin_code", models.CharField(blank=True, max_length=20)),
                ("shipping_phone", models.CharField(blank=True, max_length=50)),
                ("shipping_fax", models.CharField(blank=True, max_length=50)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "documents",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_no", models.CharField(max_length=10, unique=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="core.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billorder",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billorders",
                to="core.deal",
            ),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partial"),
                            ("DRAFT", "Draft"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("bill_date", models.DateField(db_index=True)),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryChallan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challan_number", models.CharField(max_length=50, unique=True)),
                ("place_of_supply", models.CharField(blank=True, max_length=50)),
                ("date", models.DateField()),
                (
                    "challan_type",
                    models.CharField(
                        choices=[
                            ("liquid_gas", "Supply of Liquid Gas"),
                            ("job_work", "Job work"),
                            ("approval", "Supply on Approval"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_challans",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_challans",
                        to="core.deal",
                    ),
                ),
                (
                    "delivery_challan_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deliverychallans_programmatic",
                        to="core.customerdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("CANCELLED", "Cancelled"),
                            ("SENT", "Sent"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("place_of_supply", models.CharField(blank=True, max_length=50)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount",
                        max_digits=12,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.deal",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "place_of_supply",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("quote_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "salesperson",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("customer_notes", models.TextField(blank=True, null=True)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_percentage",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5", "5%"),
                            ("12", "12%"),
                            ("18", "18%"),
                            ("28", "28%"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_quotes",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_quotes",
                        to="core.deal",
                    ),
                ),
                (
                    "quote_files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("date", models.DateField()),
                ("airway_bill", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "paid"),
                            ("Unpaid", "unpaid"),
                            ("Paid Partially", "paid partially"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                            ("None", "none"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DutyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("item_specification", models.TextField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("hsn_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "assessable_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "igst",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "social_welfare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "cess",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "duty_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "addl_duty",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_duty",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_items",
                        to="core.duty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Freight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                ("date", models.DateField(help_text="Date of the freight charge")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freight_charges",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the freight charge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freight_charges",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreightItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sf_number",
                    models.CharField(
                        blank=True,
                        help_text="Salesforce number associated with the freight charge",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight of the item",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "freight_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of freight (e.g., air, sea, land)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Unit price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Total price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "freight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.freight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                ("date", models.DateField(help_text="Date of gst")),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "paid"),
                            ("Unpaid", "unpaid"),
                            ("Paid Partially", "paid partially"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                            ("None", "none"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount of all items ",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the gst",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GstItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price",
                        max_digits=12,
                    ),
                ),
                (
                    "gst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.gst",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                ("date", models.DateField(help_text="Date of import bill for invoice")),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "paid"),
                            ("Unpaid", "unpaid"),
                            ("Paid Partially", "paid partially"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                            ("None", "none"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount of all items ",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the import bills",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price",
                        max_digits=12,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_items",
                        to="core.importbill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("CANCELLED", "Cancelled"),
                            ("SENT", "Sent"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("place_of_supply", models.CharField(blank=True, max_length=50)),
                ("invoice_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount",
                        max_digits=12,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.deal",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invoices_ui",
                        to="core.customerdocument",
                    ),
                ),
                (
                    "invoice_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invoices_programmatic",
                        to="core.customerdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_restocked_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity added to the opening stock",
                        max_digits=12,
                    ),
                ),
                (
                    "old_selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous selling price before adjustment",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "updated_selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="New selling price after adjustment",
                        max_digits=12,
                    ),
                ),
                (
                    "old_purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous purchase price before adjustment",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "updated_purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="New purchase price after adjustment",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the adjustment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "adjusted_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The item for restocking",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_adjustments",
                        to="core.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "draft_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.draftinvoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.bill",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonGst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                ("date", models.DateField(help_text="Date of nongst")),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "paid"),
                            ("Unpaid", "unpaid"),
                            ("Paid Partially", "paid partially"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                            ("None", "none"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount of all items ",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nongst_bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the gst",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nongst_bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonGstItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price",
                        max_digits=12,
                    ),
                ),
                (
                    "nongst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.nongst",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(db_index=True)),
                ("method", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "SBI"),
                            ("IOB", "IOB"),
                            ("ICICI", "ICICI"),
                            ("Petty Cash", "Petty Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("paid_on", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on"],
            },
        ),
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("place_of_supply", models.CharField(blank=True, max_length=50)),
                ("invoice_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("salesperson", models.CharField(blank=True, max_length=100)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("TDS", "TDS"), ("TCS", "TCS")],
                        default="TDS",
                        max_length=3,
                    ),
                ),
                (
                    "tax_percentage",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5", "5%"),
                            ("12", "12%"),
                            ("18", "18%"),
                            ("28", "28%"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proforma_invoices",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proforma_invoices",
                        to="core.deal",
                    ),
                ),
                (
                    "proforma_invoice_files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_number", models.CharField(max_length=50, unique=True)),
                ("place_of_supply", models.CharField(blank=True, max_length=50)),
                ("quote_date", models.DateField()),
                ("due_date", models.DateField()),
                ("salesperson", models.CharField(blank=True, max_length=100)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_percentage",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5", "5%"),
                            ("12", "12%"),
                            ("18", "18%"),
                            ("28", "28%"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="core.deal",
                    ),
                ),
                (
                    "quote_files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="preferred_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.vendor",
            ),
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("mr", "Mr"),
                            ("ms", "Ms"),
                            ("mrs", "Mrs"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("work_phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="core.customer",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billorders",
                to="core.vendor",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("invoice", "invoice_item_number")},
            },
        ),
        migrations.CreateModel(
            name="DraftQuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quote_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "draft_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.draftquote",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("draft_quote", "quote_item_number")},
            },
        ),
        migrations.CreateModel(
            name="DeliveryChallanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_challan_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "delivery_challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.deliverychallan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("delivery_challan", "delivery_challan_item_number")
                },
            },
        ),
        migrations.CreateModel(
            name="ProformaInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "proforma_invoice_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "proforma_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.proformainvoice",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("proforma_invoice", "proforma_invoice_item_number")
                },
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quote_item_number", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.quote",
                    ),
                ),
            ],
            options={
                "unique_together": {("quote", "quote_item_number")},
            },
        ),
    ]
