# Generated by Django 5.2 on 2025-09-30 08:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="customer_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "invoices_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bills_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payments_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        choices=[("Nos", "Nos"), ("Kgs", "Kgs"), ("Litres", "Litres")],
                        default="Nos",
                        max_length=10,
                    ),
                ),
                ("hsn_code", models.CharField(blank=True, max_length=20, null=True)),
                ("item_no", models.CharField(blank=True, max_length=20, null=True)),
                ("manage_sales_info", models.BooleanField(default=False)),
                (
                    "sales_selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sales_account",
                    models.CharField(blank=True, default="Sales", max_length=100),
                ),
                ("sales_description", models.TextField(blank=True)),
                ("manage_purchase_info", models.BooleanField(default=False)),
                (
                    "purchase_cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "purchase_account",
                    models.CharField(
                        blank=True, default="Cost of Goods Sold", max_length=100
                    ),
                ),
                ("purchase_description", models.TextField(blank=True)),
                ("track_inventory", models.BooleanField(default=False)),
                (
                    "opening_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "opening_stock_rate_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("individual", "Individual"),
                        ],
                        default="business",
                        max_length=20,
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("mr", "Mr"),
                            ("ms", "Ms"),
                            ("mrs", "Mrs"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("work_phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                ("pan", models.CharField(blank=True, max_length=20)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("AED", "AED"),
                            ("AUD", "AUD"),
                            ("BND", "BND"),
                            ("CAD", "CAD"),
                            ("CNY", "CNY"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("INR", "INR"),
                            ("JPY", "JPY"),
                            ("SAR", "SAR"),
                            ("USD", "USD"),
                            ("ZAR", "ZAR"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Current outstanding balance for this vendor. Updated automatically.",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("due_on_receipt", "Due on Receipt"),
                            ("net_7", "Net 7"),
                            ("net_15", "Net 15"),
                            ("net_30", "Net 30"),
                            ("net_45", "Net 45"),
                        ],
                        default="due_on_receipt",
                        max_length=20,
                    ),
                ),
                ("billing_attention", models.CharField(blank=True, max_length=255)),
                ("billing_country", models.CharField(blank=True, max_length=100)),
                ("billing_street1", models.CharField(blank=True, max_length=255)),
                ("billing_street2", models.CharField(blank=True, max_length=255)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_pin_code", models.CharField(blank=True, max_length=20)),
                ("billing_phone", models.CharField(blank=True, max_length=50)),
                ("billing_fax", models.CharField(blank=True, max_length=50)),
                ("shipping_attention", models.CharField(blank=True, max_length=255)),
                ("shipping_country", models.CharField(blank=True, max_length=100)),
                ("shipping_street1", models.CharField(blank=True, max_length=255)),
                ("shipping_street2", models.CharField(blank=True, max_length=255)),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_pin_code", models.CharField(blank=True, max_length=20)),
                ("shipping_phone", models.CharField(blank=True, max_length=50)),
                ("shipping_fax", models.CharField(blank=True, max_length=50)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("individual", "Individual"),
                        ],
                        default="business",
                        max_length=20,
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("mr", "Mr"),
                            ("ms", "Ms"),
                            ("mrs", "Mrs"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("work_phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                ("pan", models.CharField(blank=True, max_length=20)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("AED", "AED"),
                            ("AUD", "AUD"),
                            ("BND", "BND"),
                            ("CAD", "CAD"),
                            ("CNY", "CNY"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("INR", "INR"),
                            ("JPY", "JPY"),
                            ("SAR", "SAR"),
                            ("USD", "USD"),
                            ("ZAR", "ZAR"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Current outstanding balance for this customer. Updated automatically.",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("due_on_receipt", "Due on Receipt"),
                            ("net_7", "Net 7"),
                            ("net_15", "Net 15"),
                            ("net_30", "Net 30"),
                            ("net_45", "Net 45"),
                        ],
                        default="due_on_receipt",
                        max_length=20,
                    ),
                ),
                ("billing_attention", models.CharField(blank=True, max_length=255)),
                ("billing_country", models.CharField(blank=True, max_length=100)),
                ("billing_street1", models.CharField(blank=True, max_length=255)),
                ("billing_street2", models.CharField(blank=True, max_length=255)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_pin_code", models.CharField(blank=True, max_length=20)),
                ("billing_phone", models.CharField(blank=True, max_length=50)),
                ("billing_fax", models.CharField(blank=True, max_length=50)),
                ("shipping_attention", models.CharField(blank=True, max_length=255)),
                ("shipping_country", models.CharField(blank=True, max_length=100)),
                ("shipping_street1", models.CharField(blank=True, max_length=255)),
                ("shipping_street2", models.CharField(blank=True, max_length=255)),
                ("shipping_city", models.CharField(blank=True, max_length=100)),
                ("shipping_state", models.CharField(blank=True, max_length=100)),
                ("shipping_pin_code", models.CharField(blank=True, max_length=20)),
                ("shipping_phone", models.CharField(blank=True, max_length=50)),
                ("shipping_fax", models.CharField(blank=True, max_length=50)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "documents",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_no", models.CharField(max_length=10, unique=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="core.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partial"),
                            ("DRAFT", "Draft"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("bill_date", models.DateField(db_index=True)),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryChallan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challan_number", models.CharField(max_length=50, unique=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("date", models.DateField()),
                (
                    "challan_type",
                    models.CharField(
                        choices=[
                            ("liquid_gas", "Supply of Liquid Gas"),
                            ("job_work", "Job work"),
                            ("approval", "Supply on Approval"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_challans",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_challans",
                        to="core.deal",
                    ),
                ),
                (
                    "delivery_challan_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deliverychallans_programmatic",
                        to="core.customerdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("CANCELLED", "Cancelled"),
                            ("SENT", "Sent"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("order_number", models.CharField(blank=True, max_length=50)),
                ("invoice_date", models.DateField(db_index=True)),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.deal",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invoices_ui",
                        to="core.customerdocument",
                    ),
                ),
                (
                    "invoice_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invoices_programmatic",
                        to="core.customerdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_restocked_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity added to the opening stock",
                        max_digits=12,
                    ),
                ),
                (
                    "old_selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous selling price before adjustment",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "updated_selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="New selling price after adjustment",
                        max_digits=12,
                    ),
                ),
                (
                    "old_purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous purchase price before adjustment",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "updated_purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="New purchase price after adjustment",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the adjustment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "adjusted_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The item for restocking",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_adjustments",
                        to="core.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.bill",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(db_index=True)),
                ("method", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("invoice_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("salesperson", models.CharField(blank=True, max_length=100)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("TDS", "TDS"), ("TCS", "TCS")],
                        default="TDS",
                        max_length=3,
                    ),
                ),
                (
                    "tax_percentage",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5", "5%"),
                            ("12", "12%"),
                            ("18", "18%"),
                            ("28", "28%"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proforma_invoices",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proforma_invoices",
                        to="core.deal",
                    ),
                ),
                (
                    "proforma_invoice_files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_number", models.CharField(max_length=50, unique=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("quote_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("salesperson", models.CharField(blank=True, max_length=100)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("TDS", "TDS"), ("TCS", "TCS")],
                        default="TDS",
                        max_length=3,
                    ),
                ),
                (
                    "tax_percentage",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5", "5%"),
                            ("12", "12%"),
                            ("18", "18%"),
                            ("28", "28%"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="core.deal",
                    ),
                ),
                (
                    "quote_files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="preferred_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.vendor",
            ),
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("mr", "Mr"),
                            ("ms", "Ms"),
                            ("mrs", "Mrs"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("work_phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="core.customer",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("invoice", "invoice_item_number")},
            },
        ),
        migrations.CreateModel(
            name="DeliveryChallanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_challan_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "delivery_challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.deliverychallan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("delivery_challan", "delivery_challan_item_number")
                },
            },
        ),
        migrations.CreateModel(
            name="ProformaInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "proforma_invoice_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "proforma_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.proformainvoice",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("proforma_invoice", "proforma_invoice_item_number")
                },
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quote_item_number", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.quote",
                    ),
                ),
            ],
            options={
                "unique_together": {("quote", "quote_item_number")},
            },
        ),
    ]
