# Generated by Django 5.2 on 2025-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hsn_code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
