# Generated by Django 5.2 on 2025-10-26 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_bankdetail_quote_bank_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="bank_detail",
            new_name="bank_details",
        ),
    ]
