# Generated by Django 5.2 on 2025-10-01 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_item_hsn_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hsn_code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name="Freight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deal_no",
                    models.CharField(
                        help_text="Deal number associated with the freight charge",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price in USD",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price in INR",
                        max_digits=12,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the freight charge")),
                (
                    "sf_number",
                    models.CharField(
                        blank=True,
                        help_text="Salesforce number associated with the freight charge",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight of the item",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "freight_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of freight (e.g., air, sea, land)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the freight charge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freight_charges",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
    ]
