# Generated by Django 5.2 on 2025-11-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_bank_detail_quote_bank_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="is_manual_item",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="manual_hsn_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="manual_item_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="manual_item_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.item",
            ),
        ),
    ]
