# Generated by Django 5.2 on 2025-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_item_hsn_code_freight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hsn_code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
