# Generated by Django 5.2 on 2025-10-01 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_item_hsn_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freight",
            name="deal_no",
        ),
        migrations.AddField(
            model_name="freight",
            name="deal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freight_charges",
                to="core.deal",
            ),
            preserve_default=False,
        ),
    ]
