# Generated by Django 5.2 on 2025-10-02 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_freight_deal_no_freight_deal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="freight",
            old_name="total_price_inr",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="description",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="hsn_code",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="item_name",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="item_specification",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="total_price_usd",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="unit_price_inr",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="unit_price_usd",
        ),
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                ("date", models.DateField(help_text="Date of the freight charge")),
                (
                    "airway_bill",
                    models.CharField(
                        blank=True,
                        help_text="airway bill number of the duty",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "assessable_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Assessable value for this duty",
                        max_digits=12,
                    ),
                ),
                (
                    "igst",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="IGSt amount for this duty",
                        max_digits=12,
                    ),
                ),
                (
                    "social_welfare",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Social Welfare Surcharge amount",
                        max_digits=12,
                    ),
                ),
                (
                    "cess",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cess amount",
                        max_digits=12,
                    ),
                ),
                (
                    "duty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Primary duty amount",
                        max_digits=12,
                    ),
                ),
                (
                    "addl_duty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional duty amount",
                        max_digits=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount including all duties and taxes",
                        max_digits=12,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the duty",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DutyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price in USD",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_items",
                        to="core.duty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreightItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "unit_price_inr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Unit price in INR",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Total price in USD",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_price_inr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Total price in INR",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "freight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.freight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(help_text="Date of import bill for invoice"),
                ),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "paid"),
                            ("Unpaid", "unpaid"),
                            ("Paid Partially", "paid partially"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICIC", "icic"),
                            ("Petty Cash", "petty cash"),
                        ],
                        default="Petty Cash",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount of all items in  USD",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the import bills",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price in USD",
                        max_digits=12,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_items",
                        to="core.importbill",
                    ),
                ),
            ],
        ),
    ]
