# Generated by Django 5.2 on 2025-10-02 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_total_price_inr_freight_total_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freightitem",
            old_name="total_price_usd",
            new_name="total_price",
        ),
        migrations.RenameField(
            model_name="freightitem",
            old_name="unit_price_inr",
            new_name="unit_price",
        ),
        migrations.RemoveField(
            model_name="freightitem",
            name="total_price_inr",
        ),
        migrations.RemoveField(
            model_name="freightitem",
            name="unit_price_usd",
        ),
    ]
