# Generated by Django 5.2 on 2025-10-02 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_total_price_usd_freightitem_total_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="importbill",
            old_name="invoice_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="dutyitem",
            name="total_price_inr",
        ),
        migrations.RemoveField(
            model_name="dutyitem",
            name="total_price_usd",
        ),
        migrations.RemoveField(
            model_name="dutyitem",
            name="unit_price_inr",
        ),
        migrations.RemoveField(
            model_name="dutyitem",
            name="unit_price_usd",
        ),
        migrations.AddField(
            model_name="duty",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="duty",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Total price", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Unit price", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="freight",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Total price", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="freightitem",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Total price",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="freightitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Unit price",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importbill",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount of all items ",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="importbillitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Total price", max_digits=12
            ),
        ),
    ]
