# Generated by Django 5.2 on 2025-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_invoice_date_importbill_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbill",
            name="currency",
            field=models.CharField(
                default="INR", help_text="Currency of the amount", max_length=10
            ),
        ),
    ]
