# Generated by Django 5.2.4 on 2025-08-30 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_notes_proformainvoice_customer_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="notes",
            new_name="customer_notes",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="date",
            new_name="invoice_date",
        ),
        migrations.RemoveField(
            model_name="deliverychallan",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="deliverychallan",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="deliverychallan",
            name="status",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="status",
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="challan_type",
            field=models.CharField(
                choices=[
                    ("liquid_gas", "Supply of Liquid Gas"),
                    ("job_work", "Job work"),
                    ("approval", "Supply on Approval"),
                    ("others", "Others"),
                ],
                default="others",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="files",
            field=models.ManyToManyField(blank=True, to="core.customerdocument"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="order_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="terms_and_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="DeliveryChallanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.deliverychallan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
