# Generated by Django 5.2 on 2025-10-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_importbill_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbill",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                ],
                default="Petty Cash",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Gst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                ("date", models.DateField(help_text="Date of gst")),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "paid"),
                            ("Unpaid", "unpaid"),
                            ("Paid Partially", "paid partially"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                        ],
                        default="Petty Cash",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount of all items ",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the gst",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GstItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price",
                        max_digits=12,
                    ),
                ),
                (
                    "gst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.gst",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonGst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency of the amount", max_length=10
                    ),
                ),
                ("date", models.DateField(help_text="Date of nongst")),
                (
                    "payment_request",
                    models.CharField(
                        choices=[("Low", "low"), ("High", "high")],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "paid"),
                            ("Unpaid", "unpaid"),
                            ("Paid Partially", "paid partially"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                        ],
                        default="Petty Cash",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount of all items ",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nongst_bills",
                        to="core.deal",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the gst",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nongst_bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonGstItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item being shipped", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "item_specification",
                    models.TextField(
                        blank=True, help_text="Specifications of the item", null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand of the item",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN code of the item",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unit price of the item",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price",
                        max_digits=12,
                    ),
                ),
                (
                    "nongst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.nongst",
                    ),
                ),
            ],
        ),
    ]
