# Generated by Django 5.2 on 2025-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_billorder_billorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="billorder",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
