# Generated by Django 5.2.4 on 2025-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_bill_billitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
