# Generated by Django 5.2 on 2025-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_billorder_paid_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="duty",
            old_name="total",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="duty",
            name="addl_duty",
        ),
        migrations.RemoveField(
            model_name="duty",
            name="assessable_value",
        ),
        migrations.RemoveField(
            model_name="duty",
            name="cess",
        ),
        migrations.RemoveField(
            model_name="duty",
            name="duty",
        ),
        migrations.RemoveField(
            model_name="duty",
            name="igst",
        ),
        migrations.RemoveField(
            model_name="duty",
            name="social_welfare",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="freight_type",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="sf_number",
        ),
        migrations.RemoveField(
            model_name="freight",
            name="weight",
        ),
        migrations.AddField(
            model_name="billorder",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                    ("UnPaid", "unpaid"),
                ],
                default="UnPaid",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="addl_duty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional duty for this item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="assessable_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Assessable value for this item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="cess",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cess amount for this item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="igst",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="IGST amount for this item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="social_welfare",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Social welfare surcharge for this item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="total_duty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total duty (sum of all duties/taxes)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="freightitem",
            name="freight_type",
            field=models.CharField(
                blank=True,
                help_text="Type of freight (e.g., air, sea, land)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="freightitem",
            name="sf_number",
            field=models.CharField(
                blank=True,
                help_text="Salesforce number associated with the freight charge",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="freightitem",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight of the item",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="duty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Primary duty amount for this item",
                max_digits=12,
            ),
        ),
    ]
