# Generated by Django 5.2.4 on 2025-08-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_bill_bill_date_alter_invoice_invoice_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "invoices_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bills_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payments_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
