# Generated by Django 5.2 on 2025-10-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_total_duty_total_amount_remove_duty_addl_duty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyitem",
            name="duty_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Primary duty amount for this item",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="duty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duty_items",
                to="core.duty",
            ),
        ),
    ]
