# Generated by Django 5.2.4 on 2025-09-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_dailysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="quote_files",
            field=models.ManyToManyField(blank=True, to="core.customerdocument"),
        ),
    ]
