# Generated by Django 5.2.4 on 2025-09-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_quote_quote_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="proforma_invoice_files",
            field=models.ManyToManyField(blank=True, to="core.customerdocument"),
        ),
    ]
