# Generated by Django 5.2 on 2025-10-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_dutyitem_duty_amount_alter_dutyitem_duty"),
    ]

    operations = [
        migrations.AddField(
            model_name="duty",
            name="payment_reference_no",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="duty",
            name="payment_request",
            field=models.CharField(
                choices=[("Low", "low"), ("High", "high")], default="Low", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="duty",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "paid"),
                    ("Unpaid", "unpaid"),
                    ("Paid Partially", "paid partially"),
                ],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
