# Generated by Django 5.2 on 2025-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_duty_payment_reference_no_duty_payment_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="duty",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                ],
                default="Petty Cash",
                max_length=20,
            ),
        ),
    ]
