# Generated by Django 5.2.4 on 2025-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_proformainvoice_proforma_invoice_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="invoices_programmatic",
                to="core.customerdocument",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="invoices_ui", to="core.customerdocument"
            ),
        ),
    ]
