# Generated by Django 5.2.4 on 2025-09-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_invoice_invoice_files_alter_invoice_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverychallan",
            name="delivery_challan_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="deliverychallans_programmatic",
                to="core.customerdocument",
            ),
        ),
    ]
