# Generated by Django 5.2 on 2025-10-10 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_billorder_payment_reference_no"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billorder",
            name="amount_to_pay",
        ),
        migrations.RemoveField(
            model_name="billorder",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="billorder",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="billorder",
            name="total_amount",
        ),
        migrations.AlterField(
            model_name="billorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="billorder",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                ],
                default="UnPaid",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="item_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="item_specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="billorderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("SBI", "sbi"),
                            ("IOB", "iob"),
                            ("ICICI", "icici"),
                            ("Petty Cash", "petty cash"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "payment_reference_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("paid_on", models.DateTimeField(auto_now_add=True)),
                (
                    "bill_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.billorder",
                    ),
                ),
            ],
        ),
    ]
