# Generated by Django 5.2 on 2025-10-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_remove_billorder_amount_to_pay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billorder",
            name="status",
        ),
        migrations.AddField(
            model_name="billorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partial"),
                ],
                default="UnPaid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="billorder",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                ],
                default="UNPAID",
                max_length=12,
            ),
        ),
    ]
