# Generated by Django 5.2.6 on 2025-09-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_populate_quote_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='delivery_challan_item_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_item_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='proforma_invoice_item_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='deliverychallanitem',
            unique_together={('delivery_challan', 'delivery_challan_item_number')},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'invoice_item_number')},
        ),
        migrations.AlterUniqueTogether(
            name='proformainvoiceitem',
            unique_together={('proforma_invoice', 'proforma_invoice_item_number')},
        ),
    ]
