# Generated by Django 5.2 on 2025-10-10 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0019_remove_billorder_status_billorder_payment_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={"ordering": ["-paid_on"]},
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="bill_order",
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="object_id",
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billorder",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                ],
                default="Petty Cash",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="billorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Unpaid", "Unpaid"),
                    ("Paid Partially", "Paid Partially"),
                ],
                default="Unpaid",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "SBI"),
                    ("IOB", "IOB"),
                    ("ICICI", "ICICI"),
                    ("Petty Cash", "Petty Cash"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_reference_no",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
