# Generated by Django 5.2 on 2025-10-12 05:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_paymenttransaction_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="duty",
            name="airway_bill",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="duty",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="duty",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AlterField(
            model_name="duty",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="duty",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="duty",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duty",
                to="core.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="addl_duty",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="assessable_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="cess",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="duty_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="igst",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="item_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="item_specification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="social_welfare",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="total_duty",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="dutyitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="importbill",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
