# Generated by Django 5.2 on 2025-10-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_duty_airway_bill_alter_duty_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbill",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
