# Generated by Django 5.2 on 2025-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_importbill_paid_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbill",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                    ("None", "none"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
