# Generated by Django 5.2.6 on 2025-09-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_vendor_schema_alignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="address",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="phone",
        ),
    ]
