# Generated by Django 5.2 on 2025-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_duty_paid_by_alter_gst_paid_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billorder",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("SBI", "sbi"),
                    ("IOB", "iob"),
                    ("ICICI", "icici"),
                    ("Petty Cash", "petty cash"),
                    ("None", "none"),
                ],
                default="None",
                max_length=12,
            ),
        ),
    ]
