# Generated by Django 5.2 on 2025-10-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_billorder_paid_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverychallan",
            old_name="reference_number",
            new_name="place_of_supply",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="order_number",
            new_name="place_of_supply",
        ),
        migrations.RenameField(
            model_name="proformainvoice",
            old_name="reference_number",
            new_name="place_of_supply",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="reference_number",
            new_name="place_of_supply",
        ),
        migrations.CreateModel(
            name="DraftInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("CANCELLED", "Cancelled"),
                            ("SENT", "Sent"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("place_of_supply", models.CharField(blank=True, max_length=50)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("customer_notes", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.deal",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "draft_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.draftinvoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
