# Generated by Django X.Y on 2025-09-08
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0025_item_current_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10, choices=[('Nos', 'Nos'), ('Kgs', 'Kgs'), ('Litres', 'Litres')])),
                ('type', models.CharField(max_length=10, choices=[('Goods', 'Goods'), ('Service', 'Service')])),
                ('hsn_code', models.CharField(max_length=50, blank=True)),
                ('description', models.TextField(blank=True)),
                ('selling_price', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
                ('purchase_price', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
                ('tax', models.CharField(max_length=4, choices=[('18%', '18%'), ('12%', '12%'), ('5%', '5%'), ('0%', '0%')])),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(max_digits=12, decimal_places=2)),
                ('adjustment', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
                ('amount', models.DecimalField(max_digits=12, decimal_places=2)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='core.inventorymanagement')),
            ],
        ),
    ]
