# Generated by Django 5.2 on 2025-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0026_rename_reference_number_deliverychallan_place_of_supply_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="draftinvoice",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Discount amount", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="draftinvoice",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Discount amount", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage",
                max_digits=5,
            ),
        ),
    ]
