# Generated by Django 5.2 on 2025-10-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_draftinvoice_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftinvoice",
            name="adjustment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="adjustment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
