# Generated by Django 5.2 on 2025-10-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_draftinvoice_adjustment_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="adjustment",
            new_name="adjustment_amount",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="subtotal",
            new_name="gst_amount",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="tax_type",
        ),
        migrations.AddField(
            model_name="quote",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Discount amount", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="subtotal_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="DraftQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "place_of_supply",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("quote_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "salesperson",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("customer_notes", models.TextField(blank=True, null=True)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_percentage",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5", "5%"),
                            ("12", "12%"),
                            ("18", "18%"),
                            ("28", "28%"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_quotes",
                        to="core.customer",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_quotes",
                        to="core.deal",
                    ),
                ),
                (
                    "quote_files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftQuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quote_item_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "draft_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.draftquote",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("draft_quote", "quote_item_number")},
            },
        ),
    ]
