# Generated by Django 5.2.6 on 2025-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_invoice_due_date_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12),
        ),
    ]
