# Generated by Django 5.2 on 2025-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_rename_adjustment_quote_adjustment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftquote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
