# Generated by Django 5.2.6 on 2025-09-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_invoice_subtotal_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="gst_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12),
        ),
    ]
