# Generated by Django 5.2 on 2025-10-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_draftquote_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="expiry_date",
            new_name="due_date",
        ),
    ]
