# Generated by Django 5.2 on 2025-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_rename_expiry_date_quote_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftinvoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
