# Generated by Django 5.2.6 on 2025-09-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_invoice_gst_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Current outstanding balance for this customer. Updated automatically.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Current outstanding balance for this vendor. Updated automatically.",
                max_digits=12,
            ),
        ),
    ]
