# Generated by Django 5.2.6 on 2025-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_customer_current_balance_vendor_current_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverychallan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("dispatched", "Dispatched"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
