# Generated by Django 5.2 on 2025-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_draftinvoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="billorder",
            name="payment_request",
            field=models.CharField(
                choices=[("Low", "low"), ("High", "high")], default="Low", max_length=20
            ),
        ),
    ]
