# Generated by Django 5.2 on 2025-09-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_deliverychallan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="balance_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
