# Generated by Django 5.2 on 2025-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_bill_balance_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("UNPAID", "Unpaid"),
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partial"),
                    ("CANCELLED", "Cancelled"),
                    ("SENT", "Sent"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
    ]
