# Generated by Django 5.2 on 2025-09-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="billitem",
            name="deal_no",
            field=models.CharField(
                blank=True,
                help_text="Unique deal number for tracking this purchased item batch.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="deal_no",
            field=models.CharField(
                blank=True,
                help_text="Deal number referencing the purchase deal for tracking sold item history.",
                max_length=50,
            ),
        ),
    ]
