# Generated by Django 5.2 on 2025-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_billitem_deal_no_invoiceitem_deal_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
