# Generated by Django 5.2 on 2025-09-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_item_hsn_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="deal_no",
        ),
        migrations.AddField(
            model_name="invoice",
            name="deal_no",
            field=models.CharField(
                blank=True,
                help_text="Deal number referencing the purchase deal for tracking sold item history.",
                max_length=50,
            ),
        ),
    ]
