# Generated by Django 5.2 on 2025-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_remove_invoiceitem_deal_no_invoice_deal_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billitem",
            name="deal_no",
        ),
        migrations.AddField(
            model_name="bill",
            name="deal_no",
            field=models.CharField(
                blank=True,
                help_text="Deal number referencing the purchase deal for tracking sold item history.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="deal_no",
            field=models.CharField(
                blank=True,
                help_text="Deal number referencing the purchase deal for tracking sold item history.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="deal_no",
            field=models.CharField(
                blank=True,
                help_text="Deal number referencing the purchase deal for tracking sold item history.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="deal_no",
            field=models.CharField(
                blank=True,
                help_text="Deal number referencing the purchase deal for tracking sold item history.",
                max_length=50,
            ),
        ),
    ]
