# Generated by Django 5.2 on 2025-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_remove_billitem_deal_no_bill_deal_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="inventory_account",
        ),
        migrations.RemoveField(
            model_name="item",
            name="inventory_valuation_method",
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01 12:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="item_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
