# Generated by Django 5.2 on 2025-09-28 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_remove_item_inventory_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitemdetail",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="description",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="hsn_code",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="item_name",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="selling_price",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="type",
        ),
        migrations.RemoveField(
            model_name="inventorymanagement",
            name="unit",
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="added_restocked_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quantity added to the opening stock",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="adjusted_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The item for restocking",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_adjustments",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made the adjustment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="old_purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous purchase price before adjustment",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="old_selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous selling price before adjustment",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="updated_purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="New purchase price after adjustment",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="inventorymanagement",
            name="updated_selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="New selling price after adjustment",
                max_digits=12,
            ),
        ),
        migrations.DeleteModel(
            name="InventoryAdjustment",
        ),
        migrations.DeleteModel(
            name="InventoryItemDetail",
        ),
    ]
