# Generated by Django 5.2 on 2025-09-30 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_remove_inventoryitemdetail_inventory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="deal_no",
        ),
        migrations.RemoveField(
            model_name="deliverychallan",
            name="deal_no",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="deal_no",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="deal_no",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="deal_no",
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_no", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="core.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="deal",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="core.deal",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="deal",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_challans",
                to="core.deal",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="deal",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="core.deal",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="deal",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_invoices",
                to="core.deal",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="deal",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="core.deal",
            ),
            preserve_default=False,
        ),
    ]
