# Generated by Django 5.2.6 on 2025-09-12 03:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("bank", "Bank"),
                                 ("credit_card", "Credit Card")],
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("primary", models.BooleanField(default=False)),
                ("account_name", models.CharField(blank=True, max_length=128)),
                ("account_code", models.CharField(blank=True, max_length=64)),
                ("account_number", models.CharField(blank=True, max_length=64)),
                ("bank_name", models.CharField(blank=True, max_length=128)),
                ("ifsc", models.CharField(blank=True, max_length=32)),
                ("opening_balance", models.FloatField(blank=True, null=True)),
                ("current_balance", models.FloatField(default=0, editable=False)),
                ("card_number", models.CharField(blank=True, max_length=32)),
                ("card_holder_name", models.CharField(blank=True, max_length=128)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credit_limit", models.FloatField(blank=True, null=True)),
                ("issuing_bank", models.CharField(blank=True, max_length=128)),
                (
                    "statement_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "payment_due_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                ("opening_outstanding", models.FloatField(blank=True, null=True)),
                ("current_outstanding", models.FloatField(
                    default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("vendor", "Vendor"),
                            ("bank", "Bank"),
                            ("credit_card", "Credit Card"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("vendor", "Vendor"),
                            ("bank", "Bank"),
                            ("credit_card", "Credit Card"),
                        ],
                        max_length=16,
                    ),
                ),
                ("destination_id", models.PositiveIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("receipt", "Receipt"),
                            ("transfer", "Transfer"),
                            ("refund", "Refund"),
                            ("fee", "Fee"),
                            ("interest", "Interest"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.01)]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("reference_number", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="banking_tra_source__ebeafe_idx",
                    ),
                    models.Index(
                        fields=["destination_type", "destination_id"],
                        name="banking_tra_destina_847f2a_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="banking_tra_transac_201db7_idx",
                    ),
                    models.Index(fields=["date"],
                                 name="banking_tra_date_0700ea_idx"),
                ],
            },
        ),
    ]
